name: voteapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #For Dot indicator in pageView
  smooth_page_indicator: ^1.0.0+2

  #For Star rating
  smooth_star_rating_null_safety: ^1.0.4+2

  #For Country code picker
  country_calling_code_picker: ^2.0.1

  intl: ^0.18.1

  #mobX
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5

  image_picker: ^0.8.4+4

  #shared preference
  shared_preferences: ^2.1.2

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:  2.4.5
  mobx_codegen: 2.3.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
